create table legends (
  id bigint generated by default as identity primary key,
  name text,
  role text,
  fact text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insertamos datos "Semilla" para la demo
insert into legends (name, role, fact, image_url) values
('Iago Aspas', 'Capitán Eterno', 'Máximo goleador histórico. El rey de Balaídos.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/69/Iago_Aspas_2018.jpg/800px-Iago_Aspas_2018.jpg'),
('Alejandro Mostovoi', 'El Zar', 'Magia pura en los 90. Llevó al Celta a Europa.', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Aleksandr_Mostovoi.jpg'),
('Míchel Salgado', 'Muro Blanco', 'Defensa legendario. Corazón y raza gallega.', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Michel_Salgado_2008.jpg/640px-Michel_Salgado_2008.jpg');