-- 1. Banco de Preguntas (Puedes cargar 100 iniciales)
create table game_questions (
  id bigint generated by default as identity primary key,
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option char(1) not null, -- 'A', 'B', 'C' o 'D'
  difficulty int default 1, -- 1: Fácil, 2: Medio, 3: Leyenda
  category text, -- 'Historia', 'Jugadores', 'Estadio', 'Curiosidades'
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Perfil de Jugador (Extensión del usuario)
create table user_profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  total_points int default 0,
  current_streak int default 0, -- Días seguidos jugando
  max_streak int default 0,
  level int default 1, -- Novato, Promesa, Titular, Leyenda
  last_played_date date
);

-- 3. Historial de Partidas (Para evitar trampas y analizar datos)
create table game_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users,
  score int,
  questions_answered int,
  played_at timestamp with time zone default timezone('utc'::text, now())
);