-- =============================================================
-- MIGRACIÓN V1.0 · Chiño AI
-- Ranking con nombres reales + perfiles públicos
-- =============================================================

-- 1. Permitir SELECT público en user_profiles (para rankings)
DROP POLICY IF EXISTS "Perfil propio" ON user_profiles;
CREATE POLICY "Lectura pública de perfiles" ON user_profiles FOR SELECT USING (TRUE);
CREATE POLICY "Crear perfil propio" ON user_profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Actualizar perfil propio" ON user_profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Permitir SELECT público en game_sessions (para rankings)
DROP POLICY IF EXISTS "Sesiones propias" ON game_sessions;
CREATE POLICY "Lectura pública de sesiones" ON game_sessions FOR SELECT USING (TRUE);
CREATE POLICY "Crear sesión propia" ON game_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Actualizar sesión propia" ON game_sessions FOR UPDATE USING (auth.uid() = user_id);

-- 3. Añadir display_name a user_profiles (para compatibilidade)
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS display_name TEXT;

-- 4. Sistema de conocimiento: hechos verificados por usuarios
CREATE TABLE IF NOT EXISTS knowledge_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fact_text TEXT NOT NULL,
  category VARCHAR(50) DEFAULT 'general',
  verified BOOLEAN DEFAULT FALSE,
  submitted_by UUID REFERENCES auth.users,
  verified_by UUID REFERENCES auth.users,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE knowledge_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública de feitos verificados" ON knowledge_facts FOR SELECT USING (TRUE);
CREATE POLICY "Usuarios poden propor feitos" ON knowledge_facts FOR INSERT WITH CHECK (auth.uid() = submitted_by);

-- 5. Correcciones enviadas por usuarios
CREATE TABLE IF NOT EXISTS corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users,
  original_message TEXT NOT NULL,
  correction_text TEXT NOT NULL,
  category VARCHAR(50) DEFAULT 'error',
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','reviewed','accepted','rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE corrections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios poden enviar correccións" ON corrections FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admin pode ver correccións" ON corrections FOR SELECT USING (TRUE);
