-- =============================================================
-- MIGRACIÓN V1.0 · Chiño AI
-- Ranking con nombres reales + perfiles públicos
-- =============================================================

-- 1. Permitir SELECT público en user_profiles (para rankings)
DROP POLICY IF EXISTS "Perfil propio" ON user_profiles;
CREATE POLICY "Lectura pública de perfiles" ON user_profiles FOR SELECT USING (TRUE);
CREATE POLICY "Crear perfil propio" ON user_profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Actualizar perfil propio" ON user_profiles FOR UPDATE USING (auth.uid() = id);

-- 2. Permitir SELECT público en game_sessions (para rankings)
DROP POLICY IF EXISTS "Sesiones propias" ON game_sessions;
CREATE POLICY "Lectura pública de sesiones" ON game_sessions FOR SELECT USING (TRUE);
CREATE POLICY "Crear sesión propia" ON game_sessions FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Actualizar sesión propia" ON game_sessions FOR UPDATE USING (auth.uid() = user_id);

-- 3. Añadir display_name a user_profiles (para compatibilidade)
ALTER TABLE user_profiles ADD COLUMN IF NOT EXISTS display_name TEXT;

-- 4. Sistema de conocimiento: hechos verificados por usuarios
CREATE TABLE IF NOT EXISTS knowledge_facts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fact_text TEXT NOT NULL,
  category VARCHAR(50) DEFAULT 'general',
  verified BOOLEAN DEFAULT FALSE,
  submitted_by UUID REFERENCES auth.users,
  verified_by UUID REFERENCES auth.users,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE knowledge_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura pública de feitos verificados" ON knowledge_facts FOR SELECT USING (TRUE);
CREATE POLICY "Usuarios poden propor feitos" ON knowledge_facts FOR INSERT WITH CHECK (auth.uid() = submitted_by);

-- 5. Correcciones enviadas por usuarios
CREATE TABLE IF NOT EXISTS corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users,
  original_message TEXT NOT NULL,
  correction_text TEXT NOT NULL,
  category VARCHAR(50) DEFAULT 'error',
  status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending','reviewed','accepted','rejected')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE corrections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Usuarios poden enviar correccións" ON corrections FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admin pode ver correccións" ON corrections FOR SELECT USING (TRUE);

-- 6. Preguntas extra para Chiño Gamer (seed)
INSERT INTO game_questions (question_text, option_a, option_b, option_c, option_d, correct_option) VALUES
('En que ano se fundou o Celta?', '1906', '1923', '1931', '1945', 'B'),
('Quen é o máximo goleador histórico?', 'Mostovoi', 'Salgado', 'Iago Aspas', 'Gustavo López', 'C'),
('Como se chama o estadio do Celta?', 'Riazor', 'San Mamés', 'Balaídos', 'O Molinón', 'C'),
('Que xogador era O Zar?', 'Mazinho', 'Mostovoi', 'Veloso', 'Salinas', 'B'),
('Primeiro presidente do Celta?', 'Mouriño', 'Bárcena', 'Muñoz', 'Fernández', 'B'),
('Cantas Copas do Rey gañou o Celta?', '0', '1', '2', '3', 'A'),
('Cal é a mellor clasificación do Celta en LaLiga?', '3º', '4º', '5º', '6º', 'B'),
('En que ano chegou o Celta a semifinais da Europa League?', '2015', '2016', '2017', '2018', 'C'),
('A que equipo eliminou o Celta en Anfield?', 'Man Utd', 'Arsenal', 'Liverpool', 'Chelsea', 'C'),
('Cal é a capacidade actual de Balaídos?', '25.000', '29.000', '35.000', '42.000', 'B'),
('Quen é o xogador con máis partidos no Celta?', 'Aspas', 'Manolo Rodríguez', 'Salgado', 'Hugo Mallo', 'B'),
('De que dous clubs naceu o Celta en 1923?', 'Fortuna e Sporting', 'Celta FC e Vigo FC', 'Real Vigo e Athletic', 'Fortuna e Celta', 'A'),
('Que xogador do Celta gañou un Mundial?', 'Mostovoi', 'Mazinho', 'Aspas', 'Makelele', 'B'),
('En que ano inaugurouse Balaídos?', '1923', '1928', '1935', '1940', 'B'),
('Cal é o alcume de Iago Aspas?', 'O Zar', 'Príncipe das Bateas', 'O Mago', 'A Lenda', 'B'),
('Que adestrador levou ao Celta ás semis de 2017?', 'Víctor Fernández', 'Luis Enrique', 'Berizzo', 'Giráldez', 'C'),
('Cal é o máximo asistente histórico?', 'Mostovoi', 'Gustavo López', 'Aspas', 'Karpin', 'C'),
('A que equipo lle gañou o Celta 4-0 en UEFA?', 'Milan', 'Juventus', 'Inter', 'Barcelona', 'B'),
('Cal foi a maior goleada ao Dépor?', '6-0', '7-0', '13-0', '10-0', 'C'),
('Que canteirán foi traspasado por 40M€?', 'Brais Méndez', 'Gabriel Veiga', 'Hugo Mallo', 'Aspas', 'B'),
('Que xogador ruso foi icona do EuroCelta?', 'Karpin', 'Mostovoi', 'Osipov', 'Ivanov', 'B'),
('Cal é o récord de puntos do Celta en Liga?', '60', '64', '68', '72', 'B'),
('Que xogador brasileiro xogou no Celta e Dépor?', 'Ronaldo', 'Mazinho', 'Silvinho', 'Djalminha', 'C'),
('A que equipo eliminou o Celta en 99 en Anfield?', 'Liverpool', 'Man Utd', 'Arsenal', 'Chelsea', 'A'),
('Cal é o alcume de Balaídos?', 'O Fortín', 'O Templo', 'A Catedral', 'O Coliseo', 'A'),
('Que xogador do Celta foi a 4 Mundiais?', 'Aspas', 'Mostovoi', 'Makelele', 'Mazinho', 'C'),
('En que ano descendeu o Celta a Segunda?', '2004', '2005', '2007', '2011', 'C'),
('Que xogador galego é o capitán actual?', 'Míngueza', 'Aspas', 'Mallo', 'Beltrán', 'B'),
('Cantos goles fixo Borja Iglesias na 25-26?', '10', '12', '14', '16', 'C'),
('Que adestrador actual dirixe o Celta?', 'Benítez', 'Giráldez', 'Coudet', 'Berizzo', 'B')
ON CONFLICT DO NOTHING;
