-- =============================================================
-- CHIÑO AI — ESQUEMA COMPLETO PostgreSQL (Supabase)
-- Real Club Celta de Vigo · Fundado en 1923
-- Versión: 1.0 · Mayo 2026
-- =============================================================

-- 1. JUGADORES (Histórico + Plantilla Actual)
CREATE TABLE players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  full_name VARCHAR(200) GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
  birth_date DATE,
  nationality VARCHAR(100),
  position VARCHAR(50) CHECK (position IN ('Portero','Defensa','Centrocampista','Delantero','Entrenador')),
  debut_date DATE,
  last_match_date DATE,
  total_matches INT DEFAULT 0,
  total_goals INT DEFAULT 0,
  total_assists INT DEFAULT 0,
  is_legend BOOLEAN DEFAULT FALSE,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. PARTIDOS (Archivo desde 1923)
CREATE TABLE matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_date DATE NOT NULL,
  competition VARCHAR(100) NOT NULL,
  home_team VARCHAR(100) DEFAULT 'RC Celta',
  away_team VARCHAR(100) NOT NULL,
  home_score INT,
  away_score INT,
  stadium VARCHAR(100) DEFAULT 'Balaídos',
  attendance INT,
  season VARCHAR(9) NOT NULL
);

-- 3. ESTADÍSTICAS JUGADOR-PARTIDO (Para los 25 criterios del ranking)
CREATE TABLE player_match_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id BIGINT REFERENCES matches(id) ON DELETE CASCADE,
  player_id BIGINT REFERENCES players(id) ON DELETE CASCADE,
  minutes_played INT DEFAULT 0,
  goals INT DEFAULT 0,
  assists INT DEFAULT 0,
  yellow_cards INT DEFAULT 0,
  red_cards INT DEFAULT 0,
  rating DECIMAL(3,2),
  xg DECIMAL(4,2),
  xa DECIMAL(4,2),
  tackles INT DEFAULT 0,
  key_passes INT DEFAULT 0,
  dribbles_completed INT DEFAULT 0,
  pass_accuracy DECIMAL(4,2),
  ball_recoveries INT DEFAULT 0
);

-- 4. STAFF Y DIRECTIVA (Presidentes, Entrenadores, Cuerpo técnico)
CREATE TABLE staff_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  role VARCHAR(100) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE,
  notes TEXT,
  image_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. LEYENDAS (Para mostrar en la UI principal)
CREATE TABLE legends (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT,
  fact TEXT,
  image_url TEXT,
  player_id BIGINT REFERENCES players(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. PATROCINADORES Y PARTNERS
CREATE TABLE sponsors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type VARCHAR(50) CHECK (type IN ('Principal','Oficial','Técnico','Medio','Colaborador')),
  since_year INT,
  logo_url TEXT,
  is_active BOOLEAN DEFAULT TRUE
);

-- 7. PREGUNTAS DEL TRIVIAL (Chiño Gamer)
CREATE TABLE game_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option CHAR(1) NOT NULL CHECK (correct_option IN ('A','B','C','D')),
  difficulty INT DEFAULT 1 CHECK (difficulty BETWEEN 1 AND 3),
  category TEXT CHECK (category IN ('Historia','Jugadores','Estadio','Curiosidades','Actualidad')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. PERFILES DE USUARIO (Gamificación)
CREATE TABLE user_profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  total_points INT DEFAULT 0,
  current_streak INT DEFAULT 0,
  max_streak INT DEFAULT 0,
  level INT DEFAULT 1 CHECK (level BETWEEN 1 AND 10),
  last_played_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. PARTIDAS DE CHIÑO GAMER
CREATE TABLE game_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users,
  score INT DEFAULT 0,
  questions_answered INT DEFAULT 0,
  played_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. HISTORIAL DE CONVERSACIONES (Para análisis y mejora del agente)
CREATE TABLE chat_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users,
  message TEXT NOT NULL,
  role VARCHAR(20) CHECK (role IN ('user','agent')),
  lang VARCHAR(5),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- =============================================================
-- ÍNDICES PARA RENDIMIENTO
-- =============================================================
CREATE INDEX idx_players_name ON players(last_name, first_name);
CREATE INDEX idx_players_legend ON players(is_legend) WHERE is_legend = TRUE;
CREATE INDEX idx_matches_date ON matches(match_date);
CREATE INDEX idx_matches_season ON matches(season);
CREATE INDEX idx_matches_competition ON matches(competition);
CREATE INDEX idx_match_stats_player ON player_match_stats(player_id);
CREATE INDEX idx_match_stats_match ON player_match_stats(match_id);
CREATE INDEX idx_staff_role ON staff_history(role);
CREATE INDEX idx_questions_category ON game_questions(category);
CREATE INDEX idx_game_sessions_user ON game_sessions(user_id);
CREATE INDEX idx_chat_history_user ON chat_history(user_id);
CREATE INDEX idx_chat_history_created ON chat_history(created_at);

-- =============================================================
-- ROW LEVEL SECURITY (Supabase)
-- =============================================================
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_match_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE legends ENABLE ROW LEVEL SECURITY;
ALTER TABLE sponsors ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE game_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

-- Políticas: Lectura pública para datos históricos
CREATE POLICY "Lectura pública de jugadores" ON players FOR SELECT USING (TRUE);
CREATE POLICY "Lectura pública de partidos" ON matches FOR SELECT USING (TRUE);
CREATE POLICY "Lectura pública de stats" ON player_match_stats FOR SELECT USING (TRUE);
CREATE POLICY "Lectura pública de staff" ON staff_history FOR SELECT USING (TRUE);
CREATE POLICY "Lectura pública de leyendas" ON legends FOR SELECT USING (TRUE);
CREATE POLICY "Lectura pública de sponsors" ON sponsors FOR SELECT USING (TRUE);
CREATE POLICY "Lectura pública de preguntas" ON game_questions FOR SELECT USING (TRUE);

-- Perfiles y sesiones solo para usuario autenticado
CREATE POLICY "Perfil propio" ON user_profiles FOR ALL USING (auth.uid() = id);
CREATE POLICY "Sesiones propias" ON game_sessions FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Chat propio" ON chat_history FOR ALL USING (auth.uid() = user_id);
