-- ============================================================
-- Gamer Plan v2 — New Supabase Tables
-- Run this in Supabase SQL Editor (service_role required)
-- ============================================================

-- 1. user_xp: Experience, levels, streaks
CREATE TABLE IF NOT EXISTS user_xp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  xp INTEGER DEFAULT 0,
  level INTEGER DEFAULT 1,
  streak INTEGER DEFAULT 0,
  max_streak INTEGER DEFAULT 0,
  last_activity_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

-- 2. match_predictions: User match predictions
CREATE TABLE IF NOT EXISTS match_predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  match_id BIGINT NOT NULL REFERENCES match_history(id) ON DELETE CASCADE,
  predicted_result TEXT NOT NULL CHECK (predicted_result IN ('H', 'D', 'A')),
  home_goals INTEGER,
  away_goals INTEGER,
  correct BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, match_id)
);

-- 3. daily_trivia: AI-generated daily questions
CREATE TABLE IF NOT EXISTS daily_trivia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_date DATE NOT NULL UNIQUE,
  question_text TEXT NOT NULL,
  option_a TEXT NOT NULL,
  option_b TEXT NOT NULL,
  option_c TEXT NOT NULL,
  option_d TEXT NOT NULL,
  correct_option CHAR(1) NOT NULL CHECK (correct_option IN ('A','B','C','D')),
  category TEXT,
  explanation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_xp_user_id ON user_xp(user_id);
CREATE INDEX IF NOT EXISTS idx_user_xp_xp ON user_xp(xp DESC);
CREATE INDEX IF NOT EXISTS idx_match_predictions_user ON match_predictions(user_id);
CREATE INDEX IF NOT EXISTS idx_match_predictions_match ON match_predictions(match_id);
CREATE INDEX IF NOT EXISTS idx_daily_trivia_date ON daily_trivia(question_date DESC);

-- RLS: Enable row-level security
ALTER TABLE user_xp ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_trivia ENABLE ROW LEVEL SECURITY;

-- RLS Policies: user_xp
-- Users can read their own XP
DROP POLICY IF EXISTS user_xp_select_own ON user_xp;
CREATE POLICY user_xp_select_own ON user_xp
  FOR SELECT USING (auth.uid() = user_id);
-- Users can update their own XP (for upsert)
DROP POLICY IF EXISTS user_xp_insert_own ON user_xp;
CREATE POLICY user_xp_insert_own ON user_xp
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS user_xp_update_own ON user_xp;
CREATE POLICY user_xp_update_own ON user_xp
  FOR UPDATE USING (auth.uid() = user_id);

-- RLS Policies: match_predictions
DROP POLICY IF EXISTS match_predictions_select_own ON match_predictions;
CREATE POLICY match_predictions_select_own ON match_predictions
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS match_predictions_insert_own ON match_predictions;
CREATE POLICY match_predictions_insert_own ON match_predictions
  FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS match_predictions_update_own ON match_predictions;
CREATE POLICY match_predictions_update_own ON match_predictions
  FOR UPDATE USING (auth.uid() = user_id);

-- RLS Policies: daily_trivia (public read, service_role write)
DROP POLICY IF EXISTS daily_trivia_select_all ON daily_trivia;
CREATE POLICY daily_trivia_select_all ON daily_trivia
  FOR SELECT USING (true);
DROP POLICY IF EXISTS daily_trivia_insert_service ON daily_trivia;
CREATE POLICY daily_trivia_insert_service ON daily_trivia
  FOR INSERT WITH CHECK (auth.role() = 'service_role');
