export const PLANTILLA_2026 = {
  actualizada: "Maio 2026",
  entrenador: {
    nombre: "Claudio Giráldez",
    edad: 37,
    nacionalidad: "España",
    desde: "Marzo 2024",
    contrato: "2028",
    estilo: "Ofensivo, aposta pola canteira, identidade celeste",
    logros: "Clasificación europea 2025-26, cuartos UEFA Europa League"
  },
  cuerpo_tecnico: [
    "Rober Fernández — Segundo adestrador",
    "Nando Villa — Adestrador de porteiros",
    "Álex Andújar — Preparador físico",
    "Borja Oubiña — Asistente técnico",
    "Jesús García Vallejo — Analista de vídeo",
    "Pablo Pérez Urtaza — Preparador físico",
    "Gael Potti — Adestrador de porteiros",
    "Dr. Ángel Piñeiro — Médico",
  ],
  jugadores: [
    { dorsal: 13, nombre: "Ionuț Radu", posicion: "Portero", altura: 1.88, peso: 76, pie: "derecho", edad: 29, nacionalidad: "Rumanía", valor: "8,00M €", goles: 0, asistencias: 0, partidos: 28 },
    { dorsal: 1, nombre: "Iván Villar", posicion: "Portero", altura: 1.83, peso: 76, pie: "derecho", edad: 28, nacionalidad: "España", valor: "900k €", goles: 0, asistencias: 0, partidos: 12 },
    { dorsal: 25, nombre: "Marc Vidal", posicion: "Portero", altura: 1.85, peso: 80, pie: "derecho", edad: 26, nacionalidad: "España", valor: "300k €", goles: 0, asistencias: 0, partidos: 2 },
    { dorsal: 32, nombre: "Javi Rodríguez", posicion: "Defensa Central", altura: 1.78, peso: 66, pie: "derecho", edad: 22, nacionalidad: "España (Vigo)", valor: "15,00M €", goles: 2, asistencias: 1, partidos: 35 },
    { dorsal: 2, nombre: "Carl Starfelt", posicion: "Defensa Central", altura: 1.85, peso: 80, pie: "derecho", edad: 30, nacionalidad: "Suecia", valor: "5,00M €", goles: 1, asistencias: 0, partidos: 30 },
    { dorsal: 24, nombre: "Carlos Domínguez", posicion: "Defensa Central", altura: 1.87, peso: 81, pie: "derecho", edad: 25, nacionalidad: "España", valor: "3,00M €", goles: 0, asistencias: 1, partidos: 22 },
    { dorsal: 29, nombre: "Yoel Lago", posicion: "Defensa Central", altura: 1.85, peso: 70, pie: "derecho", edad: 22, nacionalidad: "España", valor: "2,50M €", goles: 1, asistencias: 0, partidos: 15 },
    { dorsal: 12, nombre: "Manu Fernández", posicion: "Defensa Central", altura: 1.85, peso: 80, pie: "derecho", edad: 25, nacionalidad: "España", valor: "1,50M €", goles: 0, asistencias: 0, partidos: 18 },
    { dorsal: 20, nombre: "Marcos Alonso", posicion: "Defensa Central / Lateral", altura: 1.88, peso: 85, pie: "esquerdo", edad: 35, nacionalidad: "España", valor: "1,40M €", goles: 2, asistencias: 1, partidos: 20 },
    { dorsal: 4, nombre: "Joseph Aidoo", posicion: "Defensa Central", altura: 1.84, peso: 80, pie: "derecho", edad: 30, nacionalidad: "Ghana", valor: "1,00M €", goles: 0, asistencias: 0, partidos: 8 },
    { dorsal: 21, nombre: "Mihailo Ristic", posicion: "Lateral Esquerdo", altura: 1.80, peso: 79, pie: "esquerdo", edad: 30, nacionalidad: "Serbia", valor: "800k €", goles: 0, asistencias: 2, partidos: 25 },
    { dorsal: 3, nombre: "Óscar Mingueza", posicion: "Lateral Dereito", altura: 1.84, peso: 75, pie: "derecho", edad: 27, nacionalidad: "España", valor: "18,00M €", goles: 3, asistencias: 4, partidos: 36 },
    { dorsal: 5, nombre: "Sergio Carreira", posicion: "Lateral Dereito", altura: 1.70, peso: 66, pie: "derecho", edad: 25, nacionalidad: "España (Vigo)", valor: "8,00M €", goles: 1, asistencias: 2, partidos: 28 },
    { dorsal: 14, nombre: "Álvaro Núñez", posicion: "Lateral Dereito", altura: 1.77, peso: 72, pie: "derecho", edad: 25, nacionalidad: "España", valor: "6,00M €", goles: 0, asistencias: 1, partidos: 20 },
    { dorsal: 17, nombre: "Javi Rueda", posicion: "Lateral Dereito", altura: 1.77, peso: 72, pie: "derecho", edad: 24, nacionalidad: "España", valor: "4,00M €", goles: 2, asistencias: 6, partidos: 32 },
    { dorsal: 16, nombre: "Miguel Román", posicion: "Medio Centro", altura: 1.78, peso: 73, pie: "derecho", edad: 23, nacionalidad: "España", valor: "15,00M €", goles: 4, asistencias: 2, partidos: 34 },
    { dorsal: 6, nombre: "Ilaix Moriba", posicion: "Medio Centro", altura: 1.85, peso: 80, pie: "derecho", edad: 23, nacionalidad: "España", valor: "10,00M €", goles: 3, asistencias: 3, partidos: 30 },
    { dorsal: 22, nombre: "Hugo Sotelo", posicion: "Medio Centro", altura: 1.80, peso: 75, pie: "derecho", edad: 22, nacionalidad: "España (Vigo)", valor: "7,50M €", goles: 2, asistencias: 3, partidos: 28 },
    { dorsal: 15, nombre: "Matías Vecino", posicion: "Medio Centro", altura: 1.89, peso: 80, pie: "derecho", edad: 34, nacionalidad: "Uruguai", valor: "1,50M €", goles: 1, asistencias: 1, partidos: 25 },
    { dorsal: 8, nombre: "Fer López", posicion: "Media Punta", altura: 1.88, peso: 80, pie: "esquerdo", edad: 22, nacionalidad: "España", valor: "16,00M €", goles: 6, asistencias: 3, partidos: 32 },
    { dorsal: 19, nombre: "Williot Swedberg", posicion: "Extremo Esquerdo", altura: 1.85, peso: 73, pie: "derecho", edad: 22, nacionalidad: "Suecia", valor: "15,00M €", goles: 5, asistencias: 5, partidos: 33 },
    { dorsal: 23, nombre: "Hugo Álvarez", posicion: "Extremo Esquerdo", altura: 1.71, peso: 70, pie: "derecho", edad: 22, nacionalidad: "España (Vigo)", valor: "8,00M €", goles: 4, asistencias: 3, partidos: 30 },
    { dorsal: 11, nombre: "Franco Cervi", posicion: "Extremo Esquerdo", altura: 1.65, peso: 67, pie: "derecho", edad: 32, nacionalidad: "Arxentina", valor: "700k €", goles: 2, asistencias: 2, partidos: 20 },
    { dorsal: 39, nombre: "Jones El-Abdellaoui", posicion: "Extremo Dereito", altura: 1.84, peso: 78, pie: "derecho", edad: 20, nacionalidad: "Noruega", valor: "8,00M €", goles: 3, asistencias: 2, partidos: 18 },
    { dorsal: 9, nombre: "Ferran Jutglà", posicion: "Extremo Dereito", altura: 1.76, peso: 71, pie: "derecho", edad: 27, nacionalidad: "España", valor: "7,00M €", goles: 9, asistencias: 3, partidos: 35 },
    { dorsal: 18, nombre: "Pablo Durán", posicion: "Dianteiro", altura: 1.76, peso: 67, pie: "derecho", edad: 25, nacionalidad: "España (Ponteareas)", valor: "4,00M €", goles: 4, asistencias: 1, partidos: 22 },
    { dorsal: 7, nombre: "Borja Iglesias", posicion: "Dianteiro", altura: 1.87, peso: 80, pie: "derecho", edad: 33, nacionalidad: "España (Santiago)", valor: "3,00M €", goles: 14, asistencias: 2, partidos: 36 },
    { dorsal: 10, nombre: "Iago Aspas (C)", posicion: "Dianteiro", altura: 1.76, peso: 67, pie: "esquerdo", edad: 38, nacionalidad: "España (Moaña)", valor: "1,80M €", goles: 5, asistencias: 3, partidos: 32 },
  ]
}
