export const REWARDS = [
  { id: 1, name: 'Insignia Celtista de Bronce', points: 500, type: 'digital', icon: '🥉', desc: 'Badge digital exclusivo para tu perfil' },
  { id: 2, name: 'Wallpaper Oficial RC Celta', points: 1000, type: 'digital', icon: '🖼️', desc: 'Fondo de pantalla HD oficial del club' },
  { id: 3, name: 'Audio Exclusivo de Chiño', points: 1500, type: 'digital', icon: '🎙️', desc: 'Mensaje de voz personalizado de Chiño' },
  { id: 4, name: 'Insignia Celtista de Plata', points: 2500, type: 'digital', icon: '🥈', desc: 'Badge plateado para tu perfil' },
  { id: 5, name: 'E-book "Historia do Celta"', points: 4000, type: 'digital', icon: '📖', desc: 'Libro digital con la historia completa del club' },
  { id: 6, name: 'Foto Firmada Digital', points: 5000, type: 'digital', icon: '🖼️', desc: 'Foto oficial firmada por la plantilla 25/26' },
  { id: 7, name: 'Insignia Celtista de Ouro', points: 7500, type: 'digital', icon: '🥇', desc: 'Badge dorado para tu perfil' },
  { id: 8, name: 'Tour Virtual 360º Balaídos', points: 10000, type: 'digital', icon: '🏟️', desc: 'Recorrido virtual interactivo por Balaídos' },
  { id: 9, name: 'Visita ao Museo do Celta', points: 15000, type: 'physical', icon: '🏛️', desc: 'Entrada gratuita al museo del club' },
  { id: 10, name: 'Bufanda Oficial', points: 20000, type: 'physical', icon: '🧣', desc: 'Bufanda oficial del RC Celta 25/26' },
  { id: 11, name: 'Visita a A Fouteza', points: 25000, type: 'physical', icon: '🌲', desc: 'Tour guiado por la ciudad deportiva' },
  { id: 12, name: 'Insignia "Lenda Celeste"', points: 35000, type: 'digital', icon: '🌟', desc: 'Badge legendario de la comunidad' },
  { id: 13, name: 'Camiseta Segunda Equipación', points: 50000, type: 'physical', icon: '👕', desc: 'Camiseta visitante 25/26 con tu nombre' },
  { id: 14, name: 'Entrada para un Partido', points: 75000, type: 'physical', icon: '🎫', desc: 'Entrada para un partido en Balaídos' },
  { id: 15, name: 'Camiseta Oficial Personalizada', points: 100000, type: 'physical', icon: '👕', desc: 'Primera equipación con nombre y dorsal' },
  { id: 16, name: 'Foto coa Primeira Plantilla', points: 125000, type: 'experience', icon: '📸', desc: 'Foto grupal con los jugadores del Celta' },
  { id: 17, name: 'Visita ao Vestiario', points: 150000, type: 'experience', icon: '🚪', desc: 'Acceso al vestuario antes de un partido' },
  { id: 18, name: 'Balón Firmado pola Plantilla', points: 200000, type: 'physical', icon: '⚽', desc: 'Balón oficial firmado por todo el equipo' },
  { id: 19, name: 'Palco VIP en Balaídos', points: 300000, type: 'experience', icon: '🥂', desc: 'Experiencia en palco con catering incluido' },
  { id: 20, name: 'Saque de Honor', points: 500000, type: 'experience', icon: '🏁', desc: 'Efectúa el saque de honor en Balaídos' },
  { id: 21, name: 'Cea cunha Lenda do Celta', points: 750000, type: 'experience', icon: '🍽️', desc: 'Cena con una leyenda histórica del club' },
  { id: 22, name: 'Abono Vitalicio', points: 1000000, type: 'physical', icon: '💎', desc: 'Abono de por vida en Balaídos' },
  { id: 23, name: 'Viaxe co Equipo a Partido Europeo', points: 2000000, type: 'experience', icon: '✈️', desc: 'Viaja con el equipo a un partido europeo' },
  { id: 24, name: 'Nome no Museo do Celta', points: 3500000, type: 'eternal', icon: '🏆', desc: 'Tu nombre grabado en el museo del club' },
  { id: 25, name: 'Asento Eterno en Balaídos', points: 5000000, type: 'eternal', icon: '👑', desc: 'Un asiento con tu nombre en Balaídos' },
]

export const REWARD_WINNERS = [
  { username: 'CelesteDeCorazón', prize: 'Visita ao Museo do Celta', prizeId: 9, points: 18200, avatar: 'CD' },
  { username: 'OuveoDeBalaídos', prize: 'Bufanda Oficial', prizeId: 10, points: 24500, avatar: 'OB' },
  { username: 'MostovoiFan99', prize: 'Visita a A Fouteza', prizeId: 11, points: 31200, avatar: 'MF' },
  { username: 'AspasEterno', prize: 'Camiseta Segunda Equipación', prizeId: 13, points: 58700, avatar: 'AE' },
  { username: 'CanteiránSempre', prize: 'Insignia "Lenda Celeste"', prizeId: 12, points: 42300, avatar: 'CS' },
  { username: 'RíaDeVigo', prize: 'Entrada para un Partido', prizeId: 14, points: 82300, avatar: 'RV' },
  { username: 'GloriaCeleste', prize: 'Entrada para un Partido', prizeId: 14, points: 79100, avatar: 'GC' },
  { username: 'BalaídosFortín', prize: 'Camiseta Oficial Personalizada', prizeId: 15, points: 112000, avatar: 'BF' },
  { username: 'MareCeleste', prize: 'Camiseta Segunda Equipación', prizeId: 13, points: 53400, avatar: 'MC' },
  { username: 'EuroCelta', prize: 'Foto coa Primeira Plantilla', prizeId: 16, points: 138000, avatar: 'EC' },
  { username: 'XogadeCoña', prize: 'Bufanda Oficial', prizeId: 10, points: 21800, avatar: 'XC' },
  { username: 'Celta1923', prize: 'Visita ao Vestiario', prizeId: 17, points: 167000, avatar: 'C2' },
  { username: 'ZonaProhibida', prize: 'Camiseta Oficial Personalizada', prizeId: 15, points: 105000, avatar: 'ZP' },
  { username: 'Mazinho10', prize: 'Insignia "Lenda Celeste"', prizeId: 12, points: 38900, avatar: 'M1' },
  { username: 'SalinasGol', prize: 'Visita a A Fouteza', prizeId: 11, points: 27800, avatar: 'SG' },
  { username: 'KarpinRuso', prize: 'Balón Firmado pola Plantilla', prizeId: 18, points: 215000, avatar: 'KR' },
  { username: 'MakeleleFan', prize: 'Palco VIP en Balaídos', prizeId: 19, points: 345000, avatar: 'MK' },
  { username: 'Veiga40M', prize: 'Camiseta Segunda Equipación', prizeId: 13, points: 55200, avatar: 'V4' },
  { username: 'Méndez10', prize: 'Bufanda Oficial', prizeId: 10, points: 23400, avatar: 'M1' },
  { username: 'MalloHugo', prize: 'Entrada para un Partido', prizeId: 14, points: 76800, avatar: 'MH' },
  { username: 'GustavoLópez', prize: 'Saque de Honor', prizeId: 20, points: 523000, avatar: 'GL' },
  { username: 'NolitoInternacional', prize: 'Cea cunha Lenda do Celta', prizeId: 21, points: 782000, avatar: 'NI' },
  { username: 'SilvinhoBrasil', prize: 'Abono Vitalicio', prizeId: 22, points: 1250000, avatar: 'SB' },
  { username: 'CatanhaGol', prize: 'Foto coa Primeira Plantilla', prizeId: 16, points: 131000, avatar: 'CG' },
  { username: 'PahiñoGoleador', prize: 'Visita ao Museo do Celta', prizeId: 9, points: 16300, avatar: 'PG' },
]
